# Week1-1: Data pre-processing for the first week

In [1]:
import pandas as pd

In [2]:
data_path = '../data/'

## Examples for creating samples for Lac1

In [4]:
# For CSV data
df1 = pd.read_csv(data_path+'Lac1_total.csv')
print(df1)

             ra        dec    xki    eta  radius  signal  noise      vr  e_vr  \
0    344.704712  41.202946  6.168 -5.290   8.358   425.0   60.8   -8.17  4.82
1    344.681000  41.197334  5.099 -5.627   8.227   621.9   64.3 -109.61  3.38
2    344.672821  41.197166  4.730 -5.637   8.128   804.3   68.0   -3.13  3.34
3    344.664093  41.191361  4.337 -5.985   8.489   214.8   54.7  -36.91  5.63
4    344.660217  41.189724  4.162 -6.083   8.598   322.1   58.5  -19.90  4.97
..          ...        ...    ...    ...     ...     ...    ...     ...   ...
164  344.487030  41.242168 -3.646 -2.937   7.877   395.8   57.2  -58.43  4.23
165  344.481171  41.274887 -3.910 -0.973   5.753   241.3   56.9 -206.85  6.08
166  344.479096  41.261890 -4.004 -1.753   6.746   372.6   61.4 -199.93  4.62
167  344.452789  41.238583 -5.189 -3.152   9.843   203.2   54.1 -125.36  6.38
168  344.449921  41.230556 -5.319 -3.633  10.616   666.0   72.0  -58.59  4.21

     P(member)
0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
..         ...
164        0.0
165        1.0
166        1.0
167        0.0
168        0.0

[169 rows x 10 columns]

In [5]:
ind_dg = df1['vr'] <= -160

In [6]:
dg = df1[ind_dg]
dg

,ra,dec,xki,eta,radius,signal,noise,vr,e_vr,P(member)
9,344.663910,41.243137,4.328,-2.878,5.209,279.1,50.5,-195.36,4.12,1.00
10,344.654999,41.235722,3.927,-3.323,5.280,382.8,47.7,-186.15,3.51,0.99
11,344.650360,41.250057,3.717,-2.463,4.468,127.4,42.0,-185.56,6.56,0.99
12,344.643341,41.225750,3.401,-3.922,5.686,629.3,54.0,-179.53,3.12,0.96
15,344.626373,41.277832,2.636,-0.797,2.920,448.3,58.6,-201.28,3.35,1.00
...,...,...,...,...,...,...,...,...,...,...
161,344.499176,41.258251,-3.098,-1.972,5.993,275.2,48.1,-195.77,4.76,1.00
162,344.493408,41.277916,-3.358,-0.792,4.895,222.1,59.8,-190.77,5.73,1.00
163,344.488220,41.251221,-3.592,-2.393,7.090,270.7,57.1,-222.08,4.97,0.98
165,344.481171,41.274887,-3.910,-0.973,5.753,241.3,56.9,-206.85,6.08,1.00
166,344.479096,41.261890,-4.004,-1.753,6.746,372.6,61.4,-199.93,4.62,1.00

In [7]:
dg.to_csv(data_path+'Lac1_dg1.csv')

In [9]:
sample1 = df1.sample(n=int(len(df1)*0.5))
sample1

,ra,dec,xki,eta,radius,signal,noise,vr,e_vr,P(member)
144,344.551300,41.268002,-0.748,-1.387,2.762,301.9,56.7,-206.87,4.60,1.0
122,344.580963,41.390278,0.589,5.950,9.819,462.3,58.0,-45.86,4.41,0.0
150,344.540070,41.318001,-1.255,1.613,2.303,358.2,57.1,-96.04,4.70,0.0
146,344.544373,41.240082,-1.061,-3.062,5.603,531.9,56.7,-115.28,4.14,0.0
6,344.614838,41.202641,2.116,-5.308,7.585,341.1,56.4,-33.05,4.19,0.0
...,...,...,...,...,...,...,...,...,...,...
9,344.663910,41.243137,4.328,-2.878,5.209,279.1,50.5,-195.36,4.12,1.0
93,344.416534,41.319027,-6.824,1.675,7.639,192.9,46.4,-207.62,5.84,1.0
37,344.570953,41.251945,0.138,-2.350,3.659,374.9,52.4,-202.11,3.54,1.0
15,344.626373,41.277832,2.636,-0.797,2.920,448.3,58.6,-201.28,3.35,1.0
49,344.550507,41.316971,-0.784,1.552,2.192,402.4,63.3,-210.20,3.17,1.0

In [10]:
sample2 = df1.sample(n=int(len(df1)*0.1))
sample2

,ra,dec,xki,eta,radius,signal,noise,vr,e_vr,P(member)
166,344.479096,41.261890,-4.004,-1.753,6.746,372.6,61.4,-199.93,4.62,1.00
7,344.670929,41.232555,4.645,-3.513,5.892,511.1,54.0,-32.86,3.43,0.00
68,344.505127,41.312973,-2.830,1.312,3.156,584.7,56.1,-53.05,3.45,0.00
0,344.704712,41.202946,6.168,-5.290,8.358,425.0,60.8,-8.17,4.82,0.00
52,344.544861,41.307056,-1.039,0.957,1.471,400.2,59.8,-194.40,4.06,1.00
129,344.572723,41.335140,0.217,2.642,4.331,253.5,57.2,-202.46,4.93,1.00
12,344.643341,41.225750,3.401,-3.922,5.686,629.3,54.0,-179.53,3.12,0.96
44,344.557678,41.295612,-0.461,0.270,0.534,317.7,55.1,-189.65,4.17,0.99
84,344.462250,41.357113,-4.763,3.960,6.341,476.3,58.7,-186.44,3.70,0.99
38,344.570465,41.281529,0.116,-0.575,0.857,198.4,48.9,-180.34,6.10,0.96
82,344.464874,41.349640,-4.645,3.512,5.891,253.7,46.1,-180.47,5.92,0.96
17,344.623749,41.269222,2.518,-1.313,2.850,364.7,48.0,-105.78,3.87,0.00
92,344.418549,41.318138,-6.733,1.622,7.546,380.8,51.2,-217.45,3.68,0.99
29,344.598114,41.231640,1.362,-3.568,5.112,278.3,48.3,-176.14,3.97,0.91
147,344.542633,41.338696,-1.139,2.855,4.079,395.6,67.1,-186.25,4.37,0.99
62,344.515625,41.329887,-2.357,2.327,3.498,382.5,61.6,-206.28,4.72,1.00

In [11]:
sample1.to_csv(data_path+'Lac1_dg_s1.csv')
sample2.to_csv(data_path+'Lac1_dg_s2.csv')

## Practice - Create the following datasets:

Group 1: 100% of Lac1 members

Group 2: 50% of Lac1 members

Group 3: 10% of Lac1 members

Group 4: 100% of Per1 members

Group 5: 10% of Cas3 members

Group 6: 50% of Cas3 members